var objectives = [
  {id: 1, type: "Keep", score: 25, map: "Center", en: "Overlook", de: "Aussichtspunkt", es: "Mirador", fr: "Belvédère"},
  {id: 2, type: "Keep", score: 25, map: "Center", en: "Valley", de: "Tal", es: "Valle", fr: "Vallée"},
  {id: 3, type: "Keep", score: 25, map: "Center", en: "Lowlands", de: "Tiefland", es: "Vega", fr: "Basses terres"},
  {id: 4, type: "Camp", score: 5, map: "Center", en: "Golanta Clearing", de: "Golanta-Lichtung", es: "Claro Golanta", fr: "Clairière de Golanta"},
  {id: 5, type: "Camp", score: 5, map: "Center", en: "Pangloss Rise", de: "Pangloss-Anhöhe", es: "Colina Pangloss", fr: "Montée de Pangloss"},
  {id: 6, type: "Camp", score: 5, map: "Center", en: "Speldan Clearcut", de: "Speldan Kahlschlag", es: "Claro Espeldia", fr: "Forêt rasée de Speldan"},
  {id: 7, type: "Camp", score: 5, map: "Center", en: "Danelon Passage", de: "Danelon-Passage", es: "Pasaje Danelon", fr: "Passage Danelon"},
  {id: 8, type: "Camp", score: 5, map: "Center", en: "Umberglade Woods", de: "Umberlichtung-Forst", es: "Bosques Clarosombra", fr: "Bois d'Ombreclair"},
  {id: 9, type: "Castle", score: 35, map: "Center", en: "Stonemist Castle", de: "Schloss Steinnebel", es: "Castillo Piedraniebla", fr: "Château Brumepierre"},
  {id: 10, type: "Camp", score: 5, map: "Center", en: "Rogue's Quarry", de: "Schurkenbruch", es: "Cantera del Pícaro", fr: "Carrière des voleurs"},
  {id: 11, type: "Tower", score: 10, map: "Center", en: "Aldon's Ledge", de: "Aldons Vorsprung", es: "Cornisa de Aldon", fr: "Corniche d'Aldon"},
  {id: 12, type: "Tower", score: 10, map: "Center", en: "Wildcreek Run'", de: "Wildbachstrecke", es: "Pista Arroyosalvaje", fr: "Piste du Ruisseau sauvage"},
  {id: 13, type: "Tower", score: 10, map: "Center", en: "Jerrifer's Slough", de: "Jerrifers Sumpfloch", es: "Cenagal de Jerrifer", fr: "Bourbier de Jerrifer"},
  {id: 14, type: "Tower", score: 10, map: "Center", en: "Klovan Gully", de: "Klovan-Senke", es: "Barranco Klovan", fr: "Petit ravin de Klovan"},
  {id: 15, type: "Tower", score: 10, map: "Center", en: "Langor Gulch", de: "Langor-Schlucht", es: "Barranco Langor", fr: "Ravin de Langor"},
  {id: 16, type: "Tower", score: 10, map: "Center", en: "Quentin Lake", de: "Quentinsee", es: "Lago Quentin", fr: "Lac Quentin"},
  {id: 17, type: "Tower", score: 10, map: "Center", en: "Mendon's Gap", de: "Mendons Spalt", es: "Zanja de Mendon", fr: "Faille de Mendon"},
  {id: 18, type: "Tower", score: 10, map: "Center", en: "Anzalias Pass", de: "Anzalias-Pass", es: "Paso Anzalias", fr: "Col d'Anzalias"},
  {id: 19, type: "Tower", score: 10, map: "Center", en: "Ogrewatch Cut", de: "Ogerwacht-Kanal", es: "Tajo de la Guardia del Ogro", fr: "Percée de Gardogre"},
  {id: 20, type: "Tower", score: 10, map: "Center", en: "Veloka Slope", de: "Veloka-Hang", es: "Pendiente Veloka", fr: "Flanc de Veloka"},
  {id: 21, type: "Tower", score: 10, map: "Center", en: "Durios Gulch", de: "Durios-Schlucht", es: "Barranco Durios", fr: "Ravin de Durios"},
  {id: 22, type: "Tower", score: 10, map: "Center", en: "Bravost Escarpment", de: "'Bravost-Abhang", es: "Escarpadura Bravost", fr: "Falaise de Bravost"},
  {id: 23, type: "Keep", score: 25, map: "BlueHome", en: "Garrison", de: "Festung", es: "Fuerte", fr: "Garnison"},
  {id: 24, type: "Camp", score: 5, map: "BlueHome", en: "Champion's demense", de: "Landgut des Champions", es: "Dominio del Campeón", fr: "Fief du champion"},
  {id: 25, type: "Tower", score: 10, map: "BlueHome", en: "Redbriar", de: "Rotdornstrauch", es: "Zarzarroja", fr: "Bruyerouge"},
  {id: 26, type: "Tower", score: 10, map: "BlueHome", en: "Greenlake", de: "Grünsee", es: "Lagoverde", fr: "Lac Vert"},
  {id: 27, type: "Keep", score: 25, map: "BlueHome", en: "Ascension Bay", de: "Bucht des Aufstiegs", es: "Bahía de la Ascensión", fr: "Baie de l'Ascension"},
  {id: 28, type: "Tower", score: 10, map: "BlueHome", en: "Dawn's Eyrie", de: "Horst der Morgendämmerung", es: "Aguilera del Alba", fr: "Promontoire de l'aube"},
  {id: 29, type: "Camp", score: 5, map: "BlueHome", en: "The Spiritholme", de: "Der Geisterholm", es: "La Isleta Espiritual", fr: "L'antre des esprits"},
  {id: 30, type: "Tower", score: 10, map: "BlueHome", en: "Woodhaven", de: "Wald-Freistatt", es: "Refugio Forestal", fr: "Gentesylve"},
  {id: 31, type: "Keep", score: 25, map: "BlueHome", en: "Askalion Hills", de: "Askalion-Hügel", es: "Colinas Askalion", fr: "Collines d'Askalion"},
  {id: 32, type: "Keep", score: 25, map: "RedHome", en: "Etheron Hills", de: "Etheron-Hügel", es: "Colinas Etheron", fr: "Collines d'Etheron"},
  {id: 33, type: "Keep", score: 25, map: "RedHome", en: "Dreaming Bay", de: "Traumbucht", es: "Bahía Onírica", fr: "Baie des rêves"},
  {id: 34, type: "Camp", score: 5, map: "RedHome", en: "Victors's Lodge", de: "Sieger-Hütte", es: "Albergue del Vencedor", fr: "Pavillon du vainqueur"},
  {id: 35, type: "Tower", score: 10, map: "RedHome", en: "Greenbriar", de: "Grünstrauch", es: "Zarzaverde", fr: "Vertebranche"},
  {id: 36, type: "Tower", score: 10, map: "RedHome", en: "Bluelake", de: "Blausee", es: "Lagoazul", fr: "Lac bleu"},
  {id: 37, type: "Keep", score: 25, map: "RedHome", en: "Garrison", de: "Festung", es: "Fuerte", fr: "Garnison"},
  {id: 38, type: "Tower", score: 10, map: "RedHome", en: "Longview", de: "Weitsicht", es: "Vistaluenga", fr: "Longuevue"},
  {id: 39, type: "Camp", score: 5, map: "RedHome", en: "The Godsword", de: "Das Gottschwert", es: "La Hoja Divina", fr: "L'Epée divine"},
  {id: 40, type: "Tower", score: 10, map: "RedHome", en: "Cliffside", de: "Felswand", es: "Despeñadero", fr: "Flanc de Falaise"},
  {id: 41, type: "Keep", score: 25, map: "GreenHome", en: "Shadaran Hills", de: "Shadaran-Hügel", es: "Colinas Shadaran", fr: "Collines de Shadaran"},
  {id: 42, type: "Tower", score: 10, map: "GreenHome", en: "Redlake", de: "Rotsee", es: "Lagorrojo", fr: "Rougelac"},
  {id: 43, type: "Camp", score: 5, map: "GreenHome", en: "Hero's Lodge", de: "Hütte des Helden", es: "Albergue del Héroe", fr: "Pavillon du Héros"},
  {id: 44, type: "Keep", score: 25, map: "GreenHome", en: "Dreadfall Bay", de: "Schreckensfall-Bucht", es: "Bahía Salto Aciago", fr: "Baie du Noir déclin"},
  {id: 45, type: "Tower", score: 10, map: "GreenHome", en: "Bluebriar", de: "Blaudornstrauch", es: "Zarzazul", fr: "Bruyazur"},
  {id: 46, type: "Keep", score: 25, map: "GreenHome", en: "Garrison", de: "Festung", es: "Fuerte", fr: "Garnison"},
  {id: 47, type: "Tower", score: 10, map: "GreenHome", en: "Sunnyhill", de: "Sonnenlichthügel", es: "Colina Soleada", fr: "Colline ensoleillée"},
  {id: 48, type: "Camp", score: 5, map: "GreenHome", en: "Faithleap", de: "Glaubenssprung", es: "Salto de Fe", fr: "Ferveur"},
  {id: 49, type: "Camp", score: 5, map: "GreenHome", en: "Bluevale Refuge", de: "Blautal-Zuflucht", es: "Refugio Valleazul", fr: "Refuge de bleubal"},
  {id: 50, type: "Camp", score: 5, map: "RedHome", en: "Bluewater Lowlands", de: "Blauwasser-Tiefland", es: "Tierras Bajas de Aguazul", fr: "Basses terres d'Eau-Azur"},
  {id: 51, type: "Camp", score: 5, map: "RedHome", en: "Astralholme", de: "Astralholm", es: "Isleta Astral", fr: "Astralholme"},
  {id: 52, type: "Camp", score: 5, map: "RedHome", en: "Arah's Hope", de: "Arahs Hoffnung", es: "Esperanza de Arah", fr: "Espoir d'Arah"},
  {id: 53, type: "Camp", score: 5, map: "RedHome", en: "Greenvale Refuge'", de: "Grüntal-Zuflucht", es: "Refugio de Valleverde", fr: "Refuge de Valvert"},
  {id: 54, type: "Camp", score: 5, map: "GreenHome", en: "Foghaven", de: "Nebel-Freistatt", es: "Refugio Neblinoso", fr: "Havre gris"},
  {id: 55, type: "Camp", score: 5, map: "GreenHome", en: "Redwater Lowlands", de: "Rotwasser-Tiefland", es: "Tierras Bajas de Aguarroja", fr: "Basses terres de Rubicon"},
  {id: 56, type: "Camp", score: 5, map: "GreenHome", en: "The Titanpaw", de: "Die Titanenpranke", es: "La Garra del Titán", fr: "Bras du titan"},
  {id: 57, type: "Tower", score: 10, map: "GreenHome", en: "Cragtop", de: "Felsenspitze", es: "Cumbrepeñasco", fr: "Sommet de l'escarpement"},
  {id: 58, type: "Camp", score: 5, map: "BlueHome", en: "Godslore", de: "Götterkunde", es: "Sabiduría de los Dioses", fr: "Divination"},
  {id: 59, type: "Camp", score: 5, map: "BlueHome", en: "Redvale Refuge", de: "Rottal-Zuflucht", es: "Refugio Vallerojo", fr: "Refuge de Valrouge"},
  {id: 60, type: "Camp", score: 5, map: "BlueHome", en: "Stargrove", de: "Sternenhain", es: "Arboleda de las Estrellas", fr: "Bosquet stellaire"},
  {id: 61, type: "Camp", score: 5, map: "BlueHome", en: "Greenwater Lowlands", de: "Grünwasser-Tiefland", es: "Tierras Bajas de Aguaverde", fr: "Basses terres d'Eau-Verdoyante"}
];