var objectives = [
  {id: 1, type: "keep", score: 25, map: "Center", en: "Overlook", de: "Aussichtspunkt", es: "", fr: "Belvédère"},
  {id: 2, type: "keep", score: 25, map: "Center", en: "Valley", de: "Tal", es: "", fr: "Vallée"},
  {id: 3, type: "keep", score: 25, map: "Center", en: "Lowlands", de: "Tiefland", es: "", fr: "Basses terres"},
  {id: 4, type: "camp", score: 5, map: "Center", en: "Golanta Clearing", de: "Golanta-Lichtung", es: "", fr: "Clairière de Golanta"},
  {id: 5, type: "camp", score: 5, map: "Center", en: "Pangloss Rise", de: "Pangloss-Anhöhe", es: "", fr: "Montée de Pangloss"},
  {id: 6, type: "camp", score: 5, map: "Center", en: "Speldan Clearcut", de: "Speldan Kahlschlag", es: "", fr: "Forêt rasée de Speldan"},
  {id: 7, type: "camp", score: 5, map: "Center", en: "Danelon Passage", de: "Danelon-Passage", es: "", fr: "Passage Danelon"},
  {id: 8, type: "camp", score: 5, map: "Center", en: "Umberglade Woods", de: "Umberlichtung-Forst", es: "", fr: "Bois d'Ombreclair"},
  {id: 9, type: "castle", score: 35, map: "Center", en: "Stonemist Castle", de: "Schloss Steinnebel", es: "", fr: "Château Brumepierre"},
  {id: 10, type: "camp", score: 5, map: "Center", en: "Rogue's Quarry", de: "Schurkenbruch", es: "", fr: "Carrière des voleurs"},
  {id: 11, type: "tower", score: 10, map: "Center", en: "Aldon's Ledge", de: "Aldons Vorsprung", es: "", fr: "Corniche d'Aldon"},
  {id: 12, type: "tower", score: 10, map: "Center", en: "Wildcreek Run'", de: "Wildbachstrecke", es: "", fr: "Piste du Ruisseau sauvage"},
  {id: 13, type: "tower", score: 10, map: "Center", en: "Jerrifer's Slough", de: "Jerrifers Sumpfloch", es: "", fr: "Bourbier de Jerrifer"},
  {id: 14, type: "tower", score: 10, map: "Center", en: "Klovan Gully", de: "Klovan-Senke", es: "", fr: "Petit ravin de Klovan"},
  {id: 15, type: "tower", score: 10, map: "Center", en: "Langor Gulch", de: "Langor-Schlucht", es: "", fr: "Ravin de Langor"},
  {id: 16, type: "tower", score: 10, map: "Center", en: "Quentin Lake", de: "Quentinsee", es: "", fr: "Lac Quentin"},
  {id: 17, type: "tower", score: 10, map: "Center", en: "Mendon's Gap", de: "Mendons Spalt", es: "", fr: "Faille de Mendon"},
  {id: 18, type: "tower", score: 10, map: "Center", en: "Anzalias Pass", de: "Anzalias-Pass", es: "", fr: "Col d'Anzalias"},
  {id: 19, type: "tower", score: 10, map: "Center", en: "Ogrewatch Cut", de: "Ogerwacht-Kanal", es: "", fr: "Percée de Gardogre"},
  {id: 20, type: "tower", score: 10, map: "Center", en: "Veloka Slope", de: "Veloka-Hang", es: "", fr: "Flanc de Veloka"},
  {id: 21, type: "tower", score: 10, map: "Center", en: "Durios Gulch", de: "Durios-Schlucht", es: "", fr: "Ravin de Durios"},
  {id: 22, type: "tower", score: 10, map: "Center", en: "Bravost Escarpment", de: "'Bravost-Abhang", es: "", fr: "Falaise de Bravost"},
  {id: 23, type: "keep", score: 25, map: "BlueHome", en: "Garrison", de: "Festung", es: "", fr: "Garnison"},
  {id: 24, type: "camp", score: 5, map: "BlueHome", en: "Champion's demense", de: "Landgut des Champions", es: "", fr: "Fief du champion"},
  {id: 25, type: "tower", score: 10, map: "BlueHome", en: "Redbriar", de: "Rotdornstrauch", es: "", fr: "Bruyerouge"},
  {id: 26, type: "tower", score: 10, map: "BlueHome", en: "Greenlake", de: "Grünsee", es: "", fr: "Lac Vert"},
  {id: 27, type: "keep", score: 25, map: "BlueHome", en: "Ascension Bay", de: "Bucht des Aufstiegs", es: "", fr: "Baie de l'Ascension"},
  {id: 28, type: "tower", score: 10, map: "BlueHome", en: "Dawn's Eyrie", de: "Horst der Morgendämmerung", es: "", fr: "Promontoire de l'aube"},
  {id: 29, type: "camp", score: 5, map: "BlueHome", en: "The Spiritholme", de: "Der Geisterholm", es: "", fr: "L'antre des esprits"},
  {id: 30, type: "tower", score: 10, map: "BlueHome", en: "Woodhaven", de: "Wald-Freistatt", es: "", fr: "Gentesylve"},
  {id: 31, type: "keep", score: 25, map: "BlueHome", en: "Askalion Hills", de: "Askalion-Hügel", es: "", fr: "Collines d'Askalion"},
  {id: 32, type: "keep", score: 25, map: "RedHome", en: "Etheron Hills", de: "Etheron-Hügel", es: "", fr: "Collines d'Etheron"},
  {id: 33, type: "keep", score: 25, map: "RedHome", en: "Dreaming Bay", de: "Traumbucht", es: "", fr: "Baie des rêves"},
  {id: 34, type: "camp", score: 5, map: "RedHome", en: "Victors's Lodge", de: "Sieger-Hütte", es: "", fr: "Pavillon du vainqueur"},
  {id: 35, type: "tower", score: 10, map: "RedHome", en: "Greenbriar", de: "Grünstrauch", es: "", fr: "Vertebranche"},
  {id: 36, type: "tower", score: 10, map: "RedHome", en: "Bluelake", de: "Blausee", es: "", fr: "Lac bleu"},
  {id: 37, type: "keep", score: 25, map: "RedHome", en: "Garrison", de: "Festung", es: "", fr: "Garnison"},
  {id: 38, type: "tower", score: 10, map: "RedHome", en: "Longview", de: "Weitsicht", es: "", fr: "Longuevue"},
  {id: 39, type: "camp", score: 5, map: "RedHome", en: "The Godsword", de: "Das Gottschwert", es: "", fr: "L'Epée divine"},
  {id: 40, type: "tower", score: 10, map: "RedHome", en: "Cliffside", de: "Felswand", es: "", fr: "Flanc de Falaise"},
  {id: 41, type: "keep", score: 25, map: "GreenHome", en: "Shadaran Hills", de: "Shadaran-Hügel", es: "", fr: "Collines de Shadaran"},
  {id: 42, type: "tower", score: 10, map: "GreenHome", en: "Redlake", de: "Rotsee", es: "", fr: "Rougelac"},
  {id: 43, type: "camp", score: 5, map: "GreenHome", en: "Hero's Lodge", de: "Hütte des Helden", es: "", fr: "Pavillon du Héros"},
  {id: 44, type: "keep", score: 25, map: "GreenHome", en: "Dreadfall Bay", de: "Schreckensfall-Bucht", es: "", fr: "Baie du Noir déclin"},
  {id: 45, type: "tower", score: 10, map: "GreenHome", en: "Bluebriar", de: "Blaudornstrauch", es: "", fr: "Bruyazur"},
  {id: 46, type: "keep", score: 25, map: "GreenHome", en: "Garrison", de: "Festung", es: "", fr: "Garnison"},
  {id: 47, type: "tower", score: 10, map: "GreenHome", en: "Sunnyhill", de: "Sonnenlichthügel", es: "", fr: "Colline ensoleillée"},
  {id: 48, type: "camp", score: 5, map: "GreenHome", en: "Faithleap", de: "Glaubenssprung", es: "", fr: "Ferveur"},
  {id: 49, type: "camp", score: 5, map: "GreenHome", en: "Bluevale Refuge", de: "Blautal-Zuflucht", es: "", fr: "Refuge de bleubal"},
  {id: 50, type: "camp", score: 5, map: "RedHome", en: "Bluewater Lowlands", de: "Blauwasser-Tiefland", es: "", fr: "Basses terres d''Eau-Azur"},
  {id: 51, type: "camp", score: 5, map: "RedHome", en: "Astralholme", de: "Astralholm", es: "", fr: "Astralholme"},
  {id: 52, type: "camp", score: 5, map: "RedHome", en: "Arah's Hope", de: "Arahs Hoffnung", es: "", fr: "Espoir d'Arah"},
  {id: 53, type: "camp", score: 5, map: "RedHome", en: "Greenvale Refuge'", de: "Grüntal-Zuflucht", es: "", fr: "Refuge de Valvert"},
  {id: 54, type: "camp", score: 5, map: "GreenHome", en: "Foghaven", de: "Nebel-Freistatt", es: "", fr: "Havre gris"},
  {id: 55, type: "camp", score: 5, map: "GreenHome", en: "Redwater Lowlands", de: "Rotwasser-Tiefland", es: "", fr: "Basses terres de Rubicon"},
  {id: 56, type: "camp", score: 5, map: "GreenHome", en: "The Titanpaw", de: "Die Titanenpranke", es: "", fr: "Bras du titan"},
  {id: 57, type: "tower", score: 10, map: "GreenHome", en: "Cragtop", de: "Felsenspitze", es: "", fr: "Sommet de l''escarpement"},
  {id: 58, type: "camp", score: 5, map: "BlueHome", en: "Godslore", de: "Götterkunde", es: "", fr: "Divination"},
  {id: 59, type: "camp", score: 5, map: "BlueHome", en: "Redvale Refuge", de: "Rottal-Zuflucht", es: "", fr: "Refuge de Valrouge"},
  {id: 60, type: "camp", score: 5, map: "BlueHome", en: "Stargrove", de: "Sternenhain", es: "", fr: "Bosquet stellaire"},
  {id: 61, type: "camp", score: 5, map: "BlueHome", en: "Greenwater Lowlands", de: "Grünwasser-Tiefland", es: "", fr: "Basses terres d''Eau-Verdoyante"}
];